- core/testing/build.gradle.kts
- core/testing/src/jvmMain/kotlin/io/github/droidkaigi/confsched/testing/robot/core/CaptureScreenRobot.jvm.kt
- gradle/libs.versions.toml
Thank you for the awesome project! @kitakkun
- close #124
- Updated Roborazzi from 1.46.1 to 1.48.0 to fix NoSuchMethodError with AbstractMainTestClock on JVM
- The 1.48.0 has a update of Compose Multiplatform which might fix the problem.
- Implemented captureNodeWithDescription for JVM platform to enable screenshot testing
- Uncommented roborazzi-compose-desktop dependency
- https://github.com/takahirom/roborazzi/actions/runs/16952566040
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fix JVM screenshot test by updating Roborazzi to 1.48.0

- feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/SponsorsScreen.kt
- close #181 
- Replaced default `Color.Black` to use MaterialTheme
- Currently this color works for both Dark/Light theme, better color scheme might be considered for light for better visibility. 
Before | After
:--: | :--:
> Changed fixed color to MaterialTheme for SponsorScreen

- CONTRIBUTING.ja.md
- CONTRIBUTING.md
- close #196 
- Fix outdated detekt commands in CONTRIBUTING.md and CONTRIBUTING.ja.md to use spotlessApply instead
- Identified that the display issue in CONTRIBUTING.ja.md (text incorrectly rendered as links) was caused by Chrome's automatic translation feature
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> docs: fix detekt command to spotlessApply in CONTRIBUTING.md and CONTRIBUTING.ja.md

- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/SaveableHelper.kt
- feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/component/ContributorsCounter.kt
- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreenPresenter.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableItemDetailContent.kt
- gradle-conventions/src/main/kotlin/droidkaigi/convention/kmp-feature.gradle.kts
Thanks for the awesome project!!
- close #215
- Compose Preview failed in Feature modules due to a version mismatch on the Android preview classpath.
- The Navigation3 line pulled Compose **runtime** to `1.9.0-SNAPSHOT` while UI/tooling stayed on `1.9.0-beta02` via the BOM, leading to `NoClassDefFoundError: SourceInformationKt`.
- **No actual Navigation3 usage was found in feature/*’ `androidMain`**, so we removed the dependency there.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> fix: Compose Preview crash in Feature modules by removing navigation3

- app-shared/src/jvmMain/kotlin/io/github/droidkaigi/confsched/JvmExternalNavController.kt
- close #164
- Implements calendar registration using the following link template on JVM/Desktop target.
- The format of dates and times must be **_ISO 8601_ basic format**.
- All url query parameters must be URL encoded.
```url
https://calendar.google.com/calendar/r/eventedit
?action=TEMPLATE
&dates=20230325T224500Z%2F20230326T001500Z  // ✅ Start and end dates and times
&stz=Europe/Brussels
&etz=Europe/Brussels
&details=EVENT_DESCRIPTION_HERE             // ✅ description
&location=EVENT_LOCATION_HERE               // ✅ location
&text=EVENT_TITLE_HERE                      // ✅ title
```
> [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
> - ✅ **basic format:** `YYYYMMDDThhmmssZ` (e.g., `20250819T103000Z`)
> - ❌ extended format: `YYYY-MM-DDThh:mm:ssZ` (e.g., `2025-08-19T10:30:00Z`)
- …
> [JVM] Implement calendar registration tap behavior in session detail

- app-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/component/GlassLikeBottomNavigationBar.kt
- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMapItem.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableTopAppBar.kt
- close https://github.com/DroidKaigi/conference-app-2025/issues/239
Replace painterResource with vectorResource for better recomposition performance:                                                                                                                                                                                                                                                               
- TimetableTopAppBar: Toggle icons (ic_view_grid, ic_view_timeline)                                                                                                        
- EventMapItem: Room icons in ToolTip component(ic_square, ic_circle, ic_diamond, ic_rhombus, ic_triangle)                                                                                                             
- …
> refactor: replace painterResource with vectorResource for vector icons

- app-android/src/main/kotlin/io/github/droidkaigi/confsched/MainActivity.kt
- close https://github.com/DroidKaigi/conference-app-2025/issues/249
- Unified the system bar background and icon colors for both light and dark modes to match the dark mode styling, providing users with a uniform UI/UX experience throughout the app.
- https://github.com/androidx/androidx/blob/androidx-main/activity/activity/src/main/java/androidx/activity/EdgeToEdge.kt
Before | After
:--: | :--:
https://github.com/user-attachments/assets/f0772048-d9e7-48bb-8205-710961143aac
> feat: uniform systemBarStyle in light/dark mode for Android App

- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/architecture/DefaultErrorFallbackContent.kt
- close #191
The fallback error screen doesn't work properly when screen size is too small or when the device is rotated to landscape mode. As the screen is not scrollable, all contents (retry button for example) is not being displayed. For now, the retry button cannot be seen and thus cannot be pressed.
This PR fixes the issue and make the screen scrollable so that all the contents be visible and interactable to the user.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/b5c17f68-7bda-48b1-9db0-09269499a603" width="300" > | <video src="https://github.com/user-attachments/assets/b5b17a9f-12f4-49ce-8c24-5d7049afee7e" width="300" >
> Make the error fallback screen scrollable

- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/LicensesScreenRoot.kt
- gradle/libs.versions.toml
downgrading aboutLibraries to 12.1.1
- close #253
- the AboutLibraries Gradle plugin v12.2.4 was crashing during IDE Gradle sync while building the KMP model (task :app-shared:findLibraries), throwing “offlineMode is final and cannot be changed.” Because of that, Android Studio only indexed androidMain and code completion broke.
- Workaround applied: I pinned the plugin in app-shared to v12.1.1. After that, Gradle sync succeeded and Android Studio recognized androidJvmMain again (no more “Kotlin not configured” / unresolved references). 
- I’m seeing similar error reports starting from 12.1.2+, and downgrading to 12.1.1 consistently fixes it here. Please take a look.
- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> fix app-shared module so that Android Studio's completion features work properly

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenContext.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenPresenter.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenUiState.kt
- close #188 
- Introduced a `selectedBookmarks` state variable in searchScreenPresenter to manage the live state of bookmarks.
- Implemented an update approach for bookmarking, where the UI is updated instantly to give the user immediate feedback.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="" width="300" > | ![untitled-ezgif com-resize](https://github.com/user-attachments/assets/9bc1b0ef-ebf4-4609-8cba-38d9e2ee7bff)
> feat: implemented bookmark state

- app-ios/CLAUDE.md
- app-ios/Makefile
- app-ios/README.md
- close #251
- Add the required setup steps to README.md.
-  Remove the command in the Makefile that were causing setup errors.
- Change the nest installation method from `brew install mtj0928/tap/nest` to use the officially documented approach
- The original approch caused `fatal: repository 'https://github.com/mtj0928/homebrew-tap/' not found`.
> Update iOS setup instructions

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt
- close #266
When displaying TimetableItemDetailScreen with 3-button navigation, the screen content doesn't extend behind the navigation bar. This PR solves this problem so that screen contents can be extended even behind the nav bar.
This PR also fixes the padding for FAB button of favorite so that it doesn't conflict with nav bar and can be seen properly above navigation bar.
Before | After
:--: | :--:
> 【TimetableItemDetailScreen】 Screen doesn't extend behind navigation bar in 3-button navigation

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/user/UserDataStore.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/session/TimetableItemCard.kt
- core/testing/build.gradle.kts
- core/testing/src/commonMain/kotlin/io/github/droidkaigi/confsched/testing/di/FavoritesScreenTestGraph.kt
- core/testing/src/commonMain/kotlin/io/github/droidkaigi/confsched/testing/di/TestAppGraph.kt
- core/testing/src/commonMain/kotlin/io/github/droidkaigi/confsched/testing/robot/favorites/FavoritesScreenRobot.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreen.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteEmpty.kt
- feature/favorites/src/commonTest/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreenTest.kt
- close #156
- implemented FavoritesScreenTest based on last year's implementation.
- However, there are some areas where DataStore does not work, so we have implemented workarounds.
- [TimetableScreenTest example](https://github.com/DroidKaigi/conference-app-2025/blob/main/feature/sessions/src/commonTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt)
- [Last year's implementation](https://github.com/DroidKaigi/conference-app-2024/blob/main/feature/favorites/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreenTest.kt)
Before | After
:--: | :--:
Before | After
:--: | :--:
> Add Screenshot Test for FavoritesScreen

- feature/profile/src/commonMain/composeResources/values-ja/strings.xml
- feature/sessions/src/commonMain/composeResources/values-ja/strings.xml
- nothing
- The titles on the session list screen and profile screen are different from Figma, so I fixed.
- I think it would be better to use the same font for the favorites and event map, but since there is no definition for it in Figma, I don't fix.
- Figma: https://www.figma.com/design/1YjyMBNVLEGcHP4W7UNzDE/DroidKaigi-2025-App-UI?node-id=54849-10371&t=x7KR47hmepg3roKC-1
Before | After | Before | After
:--: | :--: | :--: | :--:
> fix: The title of session and profile.

- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreen.kt
- feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/SponsorsScreen.kt
- close #306
- close #307 
- close #308 
- When displaying FavoritesScreen, SearchScreen, and SponsorsScreen with 3-button navigation, the screen content doesn't extend behind the navigation bar. So fixed it
- 
Before | After
:--: | :--:
Before | After
Before | After
Before | After
:--: | :--:
> fix: add contentWindowInsets to Favorites, Search, and Sponsors screens

- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/sessions/TimetableItem.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableItemDetailSummaryCard.kt
- close #315 
- For the cancelled session, the strike-through style is applied for description's text style.
- [Figma](https://www.figma.com/design/1YjyMBNVLEGcHP4W7UNzDE/DroidKaigi-2025-App-UI?node-id=54901-56792&t=rLcISEDVDKC4bFk3-4)
Before | After
:--: | :--:
Before | After
:--: | :--:
> In TimetableItemDetailSummaryCard, apply strike-through style for cancelled session

- app-ios/.editorconfig
- None
- Since Xcode 16 supports EditorConfig, this pull request adds an .editorconfig file.
This would help ensure consistent code style, such as indentation width, across users with different Xcode settings.
- https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes#Source-Editor
> Add .editorconfig for Xcode

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt
- nothing
- related to: https://github.com/DroidKaigi/conference-app-2025/issues/327
- The bottom of the Timetable Item Detail Screen overlapped with the navigation bar, so I fixed the padding.
Before | After
:--: | :--:
> fix: Timetable Item Detail Screen's bottom spacing.

- app-ios/Native/Package.swift
- app-ios/README.md
- gradle.properties
- close #334
- Replace `assembleSharedXCFramework` with `assembleSharedDebugXCFramework` in iOS instructions and code comments, since we don't need to build the release XCFramework during development.
- Remove `org.gradle.workers.max=2` from `gradle.properties` because contributors typically don't need to build the release XCFramework.
- @ry-itto: When releasing the iOS app, please generate the release XCFramework by running:
```bash
./gradlew app-shared:assembleSharedReleaseXCFramework --max-workers=1
```
This avoids the OOM build failure reported in #285.
> Remove unnecessary Gradle properties to improve build performance and update iOS build setup instructions

- .gitattributes
- close none
Added a setting to .gitattributes to normalize line endings for Kotlin files to LF.
When developing on Windows, running `./gradlew spotlessApply` formats all Kotlin files and changes the line endings to CRLF.
This issue is likely caused by a missing line ending configuration in Spotless.   
However, since this could also happen with other file generation or formatting tools, I am proposing adding this rule to `.gitattributes` to ensure consistency.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> fixed: Normalize line endings to LF

- app-ios/Native/Sources/Root/KMPConverters.swift
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/DefaultStaffApiClient.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/response/StaffResponse.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/staff/Staff.kt
- core/testing/src/commonMain/kotlin/io/github/droidkaigi/confsched/testing/robot/staff/StaffScreenRobot.kt
- feature/profile/src/commonMain/kotlin/io/github/confsched/profile/components/ProfileCardUser.kt
- feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/component/StaffItem.kt
- close #386
- The Staff type had changed from last year, causing it to no longer match the Web API type.
- By modifying it to match last year's version, the Staff screen now displays correctly.
- https://github.com/DroidKaigi/conference-app-2024/blob/57c38a76beb5b75edc9220833162e1257f40ac06/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/response/StaffResponse.kt
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/be1b0035-dc96-494e-8759-cd4f67f78c08" width="300" > | <video src="https://github.com/user-attachments/assets/1a82cede-a9e5-474d-8519-dbf049e4a658" width="300" >
> :wrench: We have made corrections to ensure StaffScreen displays correctly.

- .github/workflows/ios-build.yml
None
- In #335, an iOS build check workflow was added.
- However, it is only triggered when files under the `app-shared` directory are changed.
- This can cause build failures due to unnoticed model class changes.
- To prevent this, I added the `core/model` path to the workflow.
> [CI] Ensure KMPConverters.swift builds by adding core/model path check

- app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/naventry/SessionsNavEntry.kt
- close #313 
- Fixed issue where SearchScreen disappeared after clicking an item to view details.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/4fb84564-bac0-44b9-8cf8-ade21fd906bf" width="300" > | <video src="https://github.com/user-attachments/assets/02dc8bc2-1e52-49a2-a6fb-3e5b3386f6e5" width="300" >
> Fix: SearchScreen not visible after clicking item on wide screens

- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/LicensesScreen.kt
- close #325 
- keep library name from being omitted
- add padding for LicenseDialog
- show library name and description on LicenseDialog
Before | After
:--: | :--:
> #325 Keep library name from being omitted

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/SearchFilterRow.kt
- close #292 
- This PR is to address the issue where the filtering DropdownMenu on the search screen is cut off. #292 
Added hide function handling to explicitly lower the soft keyboard.
Use withFrameNanos to operate based on the frame used by the device.
Comparing [DroidKaigi/conference-app-2024](https://github.com/DroidKaigi/conference-app-2024) and [DroidKaigi/conference-app-2025](https://github.com/DroidKaigi/conference-app-2025), I confirmed that the Material version increased from 1.2.1 to 1.4.0.
While testing with the updated versions, we confirmed that the padding for the time delay in Dropdown has become stricter since version 1.3.1.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/846d703e-d62a-419c-a93f-e8713f2b29c2" width="300" > | <video …
> fix : cut off DropdownMenu when visible soft keyboard

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreen.kt
- close https://github.com/DroidKaigi/conference-app-2025/issues/330
- Added imePadding at SearchScreen to avoid hiding some contents
- N/A
Before | After
:--: | :--:
> fix(SearchScreen): add imePadding

- app-ios/App/AppShortcuts.xcstrings
- app-ios/App/Intents/ConferenceAppShortcutsProvider.swift
- app-ios/App/Intents/GetOngoingSessionsIntent.swift
- app-ios/App/Intents/GetSessionsAtDateIntent.swift
- app-ios/App/Intents/GetSessionsAtDateTimeIntent.swift
- app-ios/App/Intents/SessionEntity.swift
- app-ios/App/Intents/SessionsQuery.swift
- app-ios/App/Localizable.xcstrings
- app-ios/Native/Sources/Root/KMPConverters.swift
- close #121 
This PR implements App Intents to retrieve sessions, addressing issue #121.
- Added GetOngoingSessionsIntent to fetch sessions happening right now.
- Added GetSessionsAtDateIntent to fetch sessions at a specific date.
- Introduced ConferenceAppShortcutsProvider for Siri/Shortcuts integration.
- Improves real-time engagement by enabling quick voice or shortcut access to sessions.
Add shortcut movie | Call AppIntent by AppShortcuts
:--: | :--:
<video src="https://github.com/user-attachments/assets/3375b4c1-a505-4158-ab28-84d245b4bf00" width="300" > | <video src="https://github.com/user-attachments/assets/3cf362fe-2cac-41a1-9b6d-35295ffc12a2" width="300" >
> #121 add "get sessions" feature by app intent

- feature/profile/src/commonMain/kotlin/io/github/confsched/profile/ProfileEditScreen.kt
- close #385
- Set Form<Profile>.Link to ImeAction.Done in ProfileEditScreen to hide the keyboard.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/036293d3-6b53-4a9e-9d22-bd3f8060fa39" width="300" > | <video src="https://github.com/user-attachments/assets/65e5a159-843a-43cf-a3d6-da597b9922ae" width="300" >
> Set Form<Profile>.Link to ImeAction.Done in ProfileEditScreen to hide the keyboard

- feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/SponsorsScreen.kt
Originally gray was displayed, so I changed it to match the card's background color.
- close #440
- Originally gray was displayed, so I changed it to match the card's background color.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/fe65ce10-a2d1-463e-b8de-913906fe5833" width="300" > | <video src="https://github.com/user-attachments/assets/48558c19-e4a1-4faa-a325-280274ebfd05" width="300" >
> :wrench: Fixed the background color of the loading sponsor.

- app-ios/Core/Sources/Model/TimetableTimeGroupItems.swift
- When the `id` argument is omitted, the parameter defaults to `nil`, and the initializer immediately coalesces it (`id ?? UUID().uuidString`). This default-then-branch layering is redundant.
- Also, allowing call sites to pass `id: nil` (`TimetableTimeGroupItems(id: nil, ... )`) results in the same behavior as omitting the parameter. That’s not simple.
- This is a source-breaking change for call sites that explicitly pass `id: nil`; omit the parameter instead.
However, because no current call sites pass `id: nil`, the change is low-risk for our codebase; proceeding now helps prevent the optional type from propagating further.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Refactor: change id default from nil to `UUID().uuidString`

- app-ios/Native/Sources/Feature/Staff/StaffPresenter.swift
Centralize cancellation of `staffTask` in a property observer so that:
- reassigning `staffTask` always cancels the previous task, and
- setting staffTask = nil (e.g., in cleanup) cancels as well.
Of course, I think the code before the change is also good. Because it explicitly does `cancel()` even before setting `nil` to `Task`. It also does `cancel()` before setting a new `Task`. These are the evidence that he understands the specification of keeping `Task` well.
However, it is tedious to always write `cancel()`. Since it is sometimes forgotten, this PR's method to use `willSet` should be better.
- https://developer.apple.com/documentation/swift/task
- >  if you discard the reference to a task, you give up the ability to wait for that task’s result or cancel the …
> Refactor: centralize `staffTask` cancellation via property observer

- app-ios/Native/Sources/Feature/Home/HomeScreen.swift
- close ##147
- Use ToolbarItemGroup for toolbar layout.
- Apple Design Guidelines: https://developer.apple.com/design/human-interface-guidelines
- Official sample: https://developer.apple.com/documentation/SwiftUI/Landmarks-Refining-the-system-provided-glass-effect-in-toolbars
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/2bcbac80-2c3d-4eac-8de7-0f2bb25fc3c0" width="300" >
> Fix: iOS toolbar layout.

- feature/profile/src/commonMain/kotlin/io/github/confsched/profile/ProfileCardScreen.kt
- close #441
- Dynamically adjust `FlippableProfileCard` opacity based on `shareableProfileCardRenderResult`
- 0f when null (before shareable card image generation)
- 1f when not null (after shareable card image generation)
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/94eb4a8f-e62a-41e6-88d2-8fe20903acf3" width="300" > | <video src="https://github.com/user-attachments/assets/75db9343-9076-49cd-ab92-a5f6360eb713" width="300" >
> hide FlippableProfileCard while generating shareable card image

- app-shared/src/iosMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.ios.kt
- close #414 
- I implemented the web navigation section (where the ToDo items are located) in `KaigiAppUi.ios.kt` using the `navigate` function from `ExternalNavController.kt`.
<video src="https://github.com/user-attachments/assets/4a859d13-b541-4b09-a574-eb643e1534d0" width="300" >
> 【ComposeMultiplatform】Implemented the remaining web transitions for the aboutTabNavGraph

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableGridItem.kt
- close #495
- Changed TimetableSpeaker design properties to match Figma design
- style = MaterialTheme.typography.titleSmall -> style = MaterialTheme.typography.labelMedium
- color = MaterialTheme.colorScheme.onSurfaceVariant -> color = MaterialTheme.colorScheme.onSurface
- 
Before | After
:--: | :--:
> Fix change the TimetableSpeaker design propeties

- app-shared/src/iosMain/kotlin/io/github/droidkaigi/confsched/IosExternalNavController.kt
- close #476
- This was the **direct cause of the crash**.  
- On iPad, presenting a `UIActivityViewController` requires setting either `sourceView` or `barButtonItem` as an anchor.
- Since iOS 13 with multi-scene support, `keyWindow` can be `nil` or may not point to the expected window.  
- The safe approach is to retrieve the foreground `keyWindow` via `UIWindowScene`.
- In navigation/tab/stacked modal scenarios, the view controller used for presentation might not be the one actually visible.  
- The correct approach is to use `topMostViewController` to traverse and resolve the **currently visible top-most VC** before presenting.
- Deprecated https://developer.apple.com/documentation/uikit/uiapplication/keywindow
Before | After
:--: | :--:
<video …
> :wrench: We have made fixes to prevent the app from crashing when using the share feature on iPad.

- gradle-conventions/settings.gradle.kts
- settings.gradle.kts
- 
This PR optimizes dependency resolution configuration with three improvements:
- Move `google()` to first position in both `pluginManagement` and `dependencyResolutionManagement`
- Add `includeGroupByRegex` filters to restrict Google Maven repository
- Remove `gradlePluginPortal()` from `dependencyResolutionManagement`
These changes reduce unnecessary fetch requests to other repositories by prioritizing filtered Google repository searches. This also mitigates supply chain attacks where malicious libraries mimicking Google libraries could be published on Maven Central.
With these changes, "Resource missing" requests reduced from 906 to 350. 
```bash
./gradlew -m -i --refresh-dependencies assembleDevDebug 2>&1 | tee dependencies-before.log  # main branch
./gradlew -m -i …
```
> Optimize dependency repository settings

- app-android/src/main/kotlin/io/github/droidkaigi/confsched/MainActivity.kt
- close #331
- Applied a translucent scrim for the 3-button navigation
- ref: https://developer.android.com/design/ui/mobile/guides/foundations/system-bars#button_modes
- > Use a translucent three-button navigation for scrolling content. 
- The reason it was transparent even though it was translucent by default was because I was setting a transparent navigationBarStyle with `enableEdgeToEdge`.
- https://github.com/DroidKaigi/conference-app-2025/blob/63a29d2201c46f822ee787dda456edf0a1cb8085/app-android/src/main/kotlin/io/github/droidkaigi/confsched/MainActivity.kt#L14
- However, the default setting for the light theme is a white translucent scrim, which doesn't match the black-based design of this app.
- #250
- I could set the navigationBarStyle of enableEdgeToEdge to semi-transparent …
> Apply scrim for 3-button navigation

- app-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/component/KaigiNavigationScaffold.kt
- close #384
- Currently, the Bottom Navigation dodges the software keyboard to prevent overlapping. However, during composition, it could be disturbing by covering the input fields.
- We may want to leave overlapping so that the Bottom Navigation keeps under the keyboard. This PR proposes to remove IME inset consideration on the Navigation.
- N/A
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/615193a5-4e22-4f15-9e9a-6db0ecca0c90" width="300" > | <video src="https://github.com/user-attachments/assets/51dbdc08-4dcd-4046-b4ad-160adfca6800" width="300" >
> Remove software keyboard consideration on the bottom navigation not to cover input fields

- .github/workflows/remove-waiting-label.yml
- .github/workflows/save-pr-number-for-removing-waiting-label.yml
N/A
- As we did last year, introduce a label management workflow to reduce review effort.
- Nearly identical to last year’s workflow, with only minor updates to dependent actions.
How it works:
1. Manually label any PR or issue with `Waiting for response or commit`.
2. The label is automatically removed when the PR or issue is updated.
- https://github.com/DroidKaigi/conference-app-2024/blob/main/.github/workflows/save-pr-number-for-removing-waiting-label.yml
- https://github.com/DroidKaigi/conference-app-2024/blob/main/.github/workflows/remove-waiting-label.yml
> [CI] Introduce label management workflow to clarify PR status

- app-ios/Native/Sources/Component/CacheAsyncImage.swift
- app-ios/Native/Sources/Component/CircularUserIcon.swift
- app-ios/Native/Sources/Feature/Contributor/Components/ContributorListItem.swift
- app-ios/Native/Sources/Feature/Sponsor/Components/SponsorCard.swift
- app-ios/Native/Sources/Feature/Staff/Components/StaffLabel.swift
- This PR adds image caching to improve the UX
- The original `CacheAsyncImage` is from the DroidKaigi 2023 app
- https://github.com/DroidKaigi/conference-app-2023/blob/main/app-ios/Modules/Sources/Component/CacheAsyncImage.swift
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Add image caching

- app-shared/src/androidJvmMain/kotlin/io/github/droidkaigi/confsched/KaigiAppUi.androidJvm.kt
- app-shared/src/androidMain/kotlin/io/github/droidkaigi/confsched/navigation/Nav3Interop.android.kt
- close #490
As per the issue and as implemented in last year's conference app, when the back button or back gesture is used while on a tab other than the TimeTable tab, the app now navigates back to the TimeTable screen. 
Furthermore, by using `BackNavigationBehavior.PopLatest`, I have implemented a more intuitive back navigation experience. 
This change fixes an issue where the app would close on foldable devices when the back button was pressed from the About screen or Search screen.
(The issue with the About Screen was introduced with this change, but the issue with the Search Screen has been there from the beginning.)
The issue occurred because the default `BackNavigationBehavior` in `adaptive-navigation3` removes the previous all ListPane screen when a user presses the back button …
> feat: Handle back press to return to the main TimeTable tab

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt
- close #569
- Keep the scroll position in each tab. 
- Check whether the scroll position is the top or not in each tab.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/f5ec6d69-51da-46d5-a938-1db0584dc332" width="300" > | <video src="https://github.com/user-attachments/assets/01653d39-2a67-4089-9a1e-1d3420ba1143" width="300" >
> The scroll position is shared between day1 and day2 in Timetable

- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/ColorSample.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/components/AboutLinkIcon.kt
- close #410 
- In the Preview function, there were places where KaigiPreviewContainer and KaigiTheme were used, so I unified it to use KaigiPreviewContainer.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Replace KaigiTheme with KaigiPreviewContainer in preview functions

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/SearchTopBar.kt
- close #505 
- Set a placeholder string in the input field of search screen so that user can get the hints what to search
Before | After
:--: | :--:
> Set a placeholder in the input field of the search screen

- app-desktop/README.md
- close #295
- I have provided the minimum necessary information.
- Previews can be viewed from Links.
- https://github.com/Corvus400/conference-app-2025/tree/doc/create_readme_app_desktop/app-desktop
- #320
> :sparkles: Add a README for the JVM to the app-desktop module. 

- core/model/src/jvmMain/kotlin/io/github/droidkaigi/confsched/model/core/Locale.jvm.kt
- close #456 
- I implemented default locale for JVM environment.
Windows | Mac
:--: | :--:
> [JVM] Implement the JVM's getDefaultLocale

- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/session/TimetableList.kt
- close #584
This issue occurred when the following PR was merged.
It is clear from the video embedded in the PR and the VRT difference images that the problem originated from this PR.
#525
When using
```kotlin
.graphicsLayer { translationY = timetableTimeSlotOffsetY.toFloat() }
```
to move the `TimetableTimeSlot`, the slot is rendered into its own off-screen layer.
That layer is clipped to its outline (mask) when composed back into the parent.
Depending on the scroll position, this outline sometimes became a **rounded shape**, so the time text (and even any debug rectangles drawn with `drawWithContent`) appeared to be **cut off in a circular way**.
Once the slot moved past that region, the clipping outline became rectangular again, so the slot switched from *rounded → square*.
``` …
```
> :wrench: The issue where TimetableTimeSlot would sometimes be clipped in a circular manner has been addressed.

- app-ios/Native/Sources/Feature/Home/Components/TimetableGridCard.swift
- This PR fixes text alignment on the timetable card for sessions with no speakers
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Fix text alignment on timetable card

- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/RoomTheme.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableGridItem.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/grid/TimetableGrid.kt
- close #582
- The new design for TimetableGridItem has been applied.
- https://www.figma.com/design/1YjyMBNVLEGcHP4W7UNzDE/DroidKaigi-2025-App-UI?node-id=54888-47117&t=wfpvgzpRqBKy8TxY-4
Android | iOS | JVM
:--: | :--: | :--:
<video src="https://github.com/user-attachments/assets/7e8c57dc-2b52-4cb3-8105-714d78838f49" width="300" > | <video src="https://github.com/user-attachments/assets/5a51e038-c340-4541-bead-33e8908ddcbb" width="300" > | <video src="https://github.com/user-attachments/assets/f7008520-b8d6-44be-87d5-4b85634ebae4" width="300" >
> :recycle: Implement functionality to distinguish bookmark states in the timetable's grid layout mode. 

- feature/profile/src/commonMain/kotlin/io/github/confsched/profile/components/ProfileCardFront.kt
- feature/profile/src/commonMain/kotlin/io/github/confsched/profile/components/ThemeWithShape.kt
- The number of pixels in images `card_front_background_night.webp` and `card_front_background_day.webp` is large, so the performance is poor because they are directly loaded and expanded. I want to pass them through Coil.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Improve load card front background res

- feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/component/ContributorItem.kt
- feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/component/StaffItem.kt
- close #578
- This change removes the custom loading icon from the `ContributorItem` and `StaffItem` components; as a result, `SubcomposeAsyncImage`’s loading state will use the default indicator.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/0c87e378-0011-4266-8df1-8f8e83bd5c69" width="300" > | <video src="https://github.com/user-attachments/assets/c20a6308-dbe6-4e44-abe8-55718c1ab8ce" width="300" >
<video src="https://github.com/user-attachments/assets/3c2f7b84-2dbd-4d82-bcb4-6dfcac809eb5" width="300" > | <video src="https://github.com/user-attachments/assets/cb279c1b-e998-4c26-9636-57b8af021079" width="300" >
> Remove loading icon from `ContributorItem` and `StaffItem components`

- app-ios/Native/Package.swift
- app-ios/Native/Sources/Component/CircularUserIcon.swift
- app-ios/Native/Sources/Component/Resources/Localizable.xcstrings
- app-ios/Native/Sources/Component/TimetableCard.swift
- app-ios/Native/Sources/Component/TimetableGridCard.swift
- app-ios/Native/Sources/Feature/Contributor/Components/ContributorListItem.swift
- app-ios/Native/Sources/Feature/Home/Components/TimetableGridView.swift
- app-ios/Native/Sources/Feature/Home/Resources/Localizable.xcstrings
- app-ios/Native/Sources/Feature/Staff/Components/StaffLabel.swift
- none
- Apply new design to TimetableGridCard  
- Add room icon  
- Adjust CircularUserIcon (apply border to all states and add loading state)  
- Use CircularUserIcon for staff and contributors
- apply favorite button color feature (like android)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/a053e90b-d9e1-4794-9ffb-3256f7255754" width="300" > | <video src="https://github.com/user-attachments/assets/17a8da3f-b86b-41c9-8fc0-88cd0c69b239" width="300" >
> [iOS] Apply new design to TimetableGridCard and some design adjustment

- gradle.properties
- Fixes iOS Arm64 Build failed on Xcode
```
Undefined symbols for architecture arm64:
"_kfun:androidx.compose.runtime#androidx_compose_runtime_ProvidedValue$stableprop_getter$artificial(){}kotlin.Int", referenced from:
_kfun:soil.plant.compose.reacty#ErrorBoundary(androidx.compose.ui.Modifier?;kotlin.Function4<androidx.compose.foundation.layout.BoxScope,soil.plant.compose.reacty.ErrorBoundaryContext,androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>?;kotlin.Function1<kotlin.Throwable,kotlin.Unit>?;kotlin.Function0<kotlin.Unit>?;soil.plant.compose.reacty.ErrorBoundaryState?;kotlin.Function2<androidx.compose.runtime.Composer,kotlin.Int,kotlin.Unit>;androidx.compose.runtime.Composer?;kotlin.Int;kotlin.Int){} in …
```
> fix ios arm64 build

- app-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/AppGraph.kt
- app-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/KaigiApp.kt
I'm the author of the Soil library. Thank you so much for adopting Soil in this project! 
I saw how the project uses Soil and wanted to share a different implementation style that might be interesting 🙌 
This PR refactors the font family selection logic to remove dependency on SettingsScreenContext and simplify the data handling approach. 
~~This PR extracts the font family selection logic into a separate composable and leverages Soil Query's `reply.map(...).getOrNull()` pattern for cleaner data handling.~~
<details>
<summary>Not adopted: `reply.map(...).getOrNull()` pattern approach</summary>
```kotlin
// Before
val kaigiFontFamily = if (subscription.isSuccess) {
when (subscription.data) {
KaigiFontFamily.ChangoRegular -> changoFontFamily()
KaigiFontFamily.RobotoRegular -> …
```
> refactor: extract font family selection logic into separate composable

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt
- I searched through issue and PR lists but couldn't find any fixes for this problem, so I'll proceed with creating the PR.
- Currently, when you scroll in the ListTimetable screen and then navigate to another screen, the scroll position isn't preserved.
- To improve user experience, I've modified the implementation to maintain LazyListState, effectively resolving this issue.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/e2371003-4cd5-42c3-868d-f6c71f3f83ba" width="300" > | <video src="https://github.com/user-attachments/assets/c8d281f5-d913-43cc-8158-c88bf352e7f0" width="300" >
> fix: timetable didn't retain scroll position

- app-ios/Native/Sources/Feature/TimetableDetail/Resources/Localizable.xcstrings
- app-ios/Native/Sources/Feature/TimetableDetail/TimetableDetailScreen.swift
- close #617 
This PR improves the session detail UI by relocating archive-related actions from the FAB menu to a dedicated archive section, following Material Design 3 guidelines.
Following Figma design specifications:
- **Added Archive section** below Target Audience section with video and slides buttons (moved from FAB menu)
- **Applied Room theme colors** to archive buttons for visual consistency
- **Updated button labels**: "Watch video" → "Video", "Open presentation slides" → "Slides"
- **Implemented conditional display** using `asset.isAvailable` (will show/hide based on content availability)
- Archive section will display actual content when video/slide URLs are available from the backend
- Removed unused localization strings for the old button labels
- [Material Design 3 - FAB …
> [iOS] Move session archive buttons from FAB to dedicated section

- core/testing/src/commonMain/kotlin/io/github/droidkaigi/confsched/testing/robot/sessions/TimetableItemDetailScreenRobot.kt
- feature/sessions/src/commonMain/composeResources/values-ja/strings.xml
- feature/sessions/src/commonMain/composeResources/values/strings.xml
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableItemDetailAnnounceMessage.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableItemDetailContent.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableItemDetailFloatingMenu.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableItemDetailHeadline.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/components/TimetableItemDetailSummaryCard.kt
- #506
- Improved Talkback feedback and traversal order for timetable detail.
- Read more button has been adjusted to match Figma's specifications.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/d817b6a4-fafe-46fd-939e-a8443718aed3" width="300" /> | <video src="https://github.com/user-attachments/assets/a2b61d31-9ed1-406c-849a-6b749794a0c9" width="300" />
> Improve timetable detail talkback feedback

- core/droidkaigiui/src/androidMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/OrientationSensorManager.android.kt
- core/droidkaigiui/src/androidMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/WithDeviceOrientation.android.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/OrientationSensorManager.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/WithDeviceOrientation.kt
- core/droidkaigiui/src/iosMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/OrientationSensorManager.ios.kt
- core/droidkaigiui/src/iosMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/WithDeviceOrientation.ios.kt
- core/droidkaigiui/src/jvmMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/OrientationSensorManager.jvm.kt
- core/droidkaigiui/src/jvmMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/WithDeviceOrientation.jvm.kt
- feature/profile/src/commonMain/kotlin/io/github/confsched/profile/HologramaticEffectModifier.kt
- feature/profile/src/commonMain/kotlin/io/github/confsched/profile/TiltEffectModifier.kt
- feature/profile/src/commonMain/kotlin/io/github/confsched/profile/components/FlippableProfileCard.kt
- close #353
- This code is essentially a copy-paste of last year's implementation.
- While Figma's requirements for sparkle have changed since last year, there's no realistic chance of implementing the new version within the remaining time, so we've kept last year's version.
- Additionally, testing is currently blocked by another person's task, so it's not included in this PR.
- We haven't been able to verify functionality on iOS this year because we can't install apps on actual devices.
- https://github.com/DroidKaigi/conference-app-2024/pull/910
- https://github.com/DroidKaigi/conference-app-2024/pull/750
- #157
- https://www.figma.com/design/1YjyMBNVLEGcHP4W7UNzDE/DroidKaigi-2025-App-UI?node-id=55884-7807&t=Ip7JuwznH0cykPlh-4
Android | iOS
:--: | :--:
<video …
> :sparkles: We implemented a feature that uses the device's sensors to make the card tilt and light up. 
